name: Release Action

on:
  release:
    types: [published]
    branches: [ main ]
    
# allow manual activation
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Run sample output check if working
      run: echo Hello! 
    
